export const AUTH_CONSTANTS = {
  BCRYPT_SALT_ROUNDS: 10,
  VERIFY_LINK_EXPIRY_MINUTES: 10,
  TOKEN_PURPOSE: {
    VERIFY_EMAIL: 'VERIFY_EMAIL',
    RESET_PASSWORD: 'RESET_PASSWORD',
  },
} as const;
